// Generated by gencpp from file learning_communication/AddTwoInts.msg
// DO NOT EDIT!


#ifndef LEARNING_COMMUNICATION_MESSAGE_ADDTWOINTS_H
#define LEARNING_COMMUNICATION_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <learning_communication/AddTwoIntsRequest.h>
#include <learning_communication/AddTwoIntsResponse.h>


namespace learning_communication
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace learning_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learning_communication::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::learning_communication::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::learning_communication::AddTwoInts > {
  static const char* value()
  {
    return "learning_communication/AddTwoInts";
  }

  static const char* value(const ::learning_communication::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::learning_communication::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::learning_communication::AddTwoInts > 
template<>
struct MD5Sum< ::learning_communication::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learning_communication::AddTwoInts >::value();
  }
  static const char* value(const ::learning_communication::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_communication::AddTwoIntsRequest> should match 
// service_traits::DataType< ::learning_communication::AddTwoInts > 
template<>
struct DataType< ::learning_communication::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::learning_communication::AddTwoInts >::value();
  }
  static const char* value(const ::learning_communication::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learning_communication::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::learning_communication::AddTwoInts > 
template<>
struct MD5Sum< ::learning_communication::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learning_communication::AddTwoInts >::value();
  }
  static const char* value(const ::learning_communication::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_communication::AddTwoIntsResponse> should match 
// service_traits::DataType< ::learning_communication::AddTwoInts > 
template<>
struct DataType< ::learning_communication::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::learning_communication::AddTwoInts >::value();
  }
  static const char* value(const ::learning_communication::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARNING_COMMUNICATION_MESSAGE_ADDTWOINTS_H
