(cl:defpackage map_msgs-msg
  (:use )
  (:export
   "<OCCUPANCYGRIDUPDATE>"
   "OCCUPANCYGRIDUPDATE"
   "<POINTCLOUD2UPDATE>"
   "POINTCLOUD2UPDATE"
   "<PROJECTEDMAP>"
   "PROJECTEDMAP"
   "<PROJECTEDMAPINFO>"
   "PROJECTEDMAPINFO"
  ))

