// Generated by gencpp from file map_msgs/GetMapROI.msg
// DO NOT EDIT!


#ifndef MAP_MSGS_MESSAGE_GETMAPROI_H
#define MAP_MSGS_MESSAGE_GETMAPROI_H

#include <ros/service_traits.h>


#include <map_msgs/GetMapROIRequest.h>
#include <map_msgs/GetMapROIResponse.h>


namespace map_msgs
{

struct GetMapROI
{

typedef GetMapROIRequest Request;
typedef GetMapROIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMapROI
} // namespace map_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_msgs::GetMapROI > {
  static const char* value()
  {
    return "81aa75ecf00f4571a9be0d9dc6dea512";
  }

  static const char* value(const ::map_msgs::GetMapROI&) { return value(); }
};

template<>
struct DataType< ::map_msgs::GetMapROI > {
  static const char* value()
  {
    return "map_msgs/GetMapROI";
  }

  static const char* value(const ::map_msgs::GetMapROI&) { return value(); }
};


// service_traits::MD5Sum< ::map_msgs::GetMapROIRequest> should match 
// service_traits::MD5Sum< ::map_msgs::GetMapROI > 
template<>
struct MD5Sum< ::map_msgs::GetMapROIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_msgs::GetMapROI >::value();
  }
  static const char* value(const ::map_msgs::GetMapROIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_msgs::GetMapROIRequest> should match 
// service_traits::DataType< ::map_msgs::GetMapROI > 
template<>
struct DataType< ::map_msgs::GetMapROIRequest>
{
  static const char* value()
  {
    return DataType< ::map_msgs::GetMapROI >::value();
  }
  static const char* value(const ::map_msgs::GetMapROIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_msgs::GetMapROIResponse> should match 
// service_traits::MD5Sum< ::map_msgs::GetMapROI > 
template<>
struct MD5Sum< ::map_msgs::GetMapROIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_msgs::GetMapROI >::value();
  }
  static const char* value(const ::map_msgs::GetMapROIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_msgs::GetMapROIResponse> should match 
// service_traits::DataType< ::map_msgs::GetMapROI > 
template<>
struct DataType< ::map_msgs::GetMapROIResponse>
{
  static const char* value()
  {
    return DataType< ::map_msgs::GetMapROI >::value();
  }
  static const char* value(const ::map_msgs::GetMapROIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_MSGS_MESSAGE_GETMAPROI_H
