// Generated by gencpp from file map_msgs/GetPointMapROI.msg
// DO NOT EDIT!


#ifndef MAP_MSGS_MESSAGE_GETPOINTMAPROI_H
#define MAP_MSGS_MESSAGE_GETPOINTMAPROI_H

#include <ros/service_traits.h>


#include <map_msgs/GetPointMapROIRequest.h>
#include <map_msgs/GetPointMapROIResponse.h>


namespace map_msgs
{

struct GetPointMapROI
{

typedef GetPointMapROIRequest Request;
typedef GetPointMapROIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPointMapROI
} // namespace map_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_msgs::GetPointMapROI > {
  static const char* value()
  {
    return "d955594b5ccde9615cbe5aed9442f733";
  }

  static const char* value(const ::map_msgs::GetPointMapROI&) { return value(); }
};

template<>
struct DataType< ::map_msgs::GetPointMapROI > {
  static const char* value()
  {
    return "map_msgs/GetPointMapROI";
  }

  static const char* value(const ::map_msgs::GetPointMapROI&) { return value(); }
};


// service_traits::MD5Sum< ::map_msgs::GetPointMapROIRequest> should match 
// service_traits::MD5Sum< ::map_msgs::GetPointMapROI > 
template<>
struct MD5Sum< ::map_msgs::GetPointMapROIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_msgs::GetPointMapROI >::value();
  }
  static const char* value(const ::map_msgs::GetPointMapROIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_msgs::GetPointMapROIRequest> should match 
// service_traits::DataType< ::map_msgs::GetPointMapROI > 
template<>
struct DataType< ::map_msgs::GetPointMapROIRequest>
{
  static const char* value()
  {
    return DataType< ::map_msgs::GetPointMapROI >::value();
  }
  static const char* value(const ::map_msgs::GetPointMapROIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_msgs::GetPointMapROIResponse> should match 
// service_traits::MD5Sum< ::map_msgs::GetPointMapROI > 
template<>
struct MD5Sum< ::map_msgs::GetPointMapROIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_msgs::GetPointMapROI >::value();
  }
  static const char* value(const ::map_msgs::GetPointMapROIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_msgs::GetPointMapROIResponse> should match 
// service_traits::DataType< ::map_msgs::GetPointMapROI > 
template<>
struct DataType< ::map_msgs::GetPointMapROIResponse>
{
  static const char* value()
  {
    return DataType< ::map_msgs::GetPointMapROI >::value();
  }
  static const char* value(const ::map_msgs::GetPointMapROIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_MSGS_MESSAGE_GETPOINTMAPROI_H
