// Generated by gencpp from file map_msgs/GetPointMap.msg
// DO NOT EDIT!


#ifndef MAP_MSGS_MESSAGE_GETPOINTMAP_H
#define MAP_MSGS_MESSAGE_GETPOINTMAP_H

#include <ros/service_traits.h>


#include <map_msgs/GetPointMapRequest.h>
#include <map_msgs/GetPointMapResponse.h>


namespace map_msgs
{

struct GetPointMap
{

typedef GetPointMapRequest Request;
typedef GetPointMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPointMap
} // namespace map_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_msgs::GetPointMap > {
  static const char* value()
  {
    return "b84fbb39505086eb6a62d933c75cb7b4";
  }

  static const char* value(const ::map_msgs::GetPointMap&) { return value(); }
};

template<>
struct DataType< ::map_msgs::GetPointMap > {
  static const char* value()
  {
    return "map_msgs/GetPointMap";
  }

  static const char* value(const ::map_msgs::GetPointMap&) { return value(); }
};


// service_traits::MD5Sum< ::map_msgs::GetPointMapRequest> should match 
// service_traits::MD5Sum< ::map_msgs::GetPointMap > 
template<>
struct MD5Sum< ::map_msgs::GetPointMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_msgs::GetPointMap >::value();
  }
  static const char* value(const ::map_msgs::GetPointMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_msgs::GetPointMapRequest> should match 
// service_traits::DataType< ::map_msgs::GetPointMap > 
template<>
struct DataType< ::map_msgs::GetPointMapRequest>
{
  static const char* value()
  {
    return DataType< ::map_msgs::GetPointMap >::value();
  }
  static const char* value(const ::map_msgs::GetPointMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_msgs::GetPointMapResponse> should match 
// service_traits::MD5Sum< ::map_msgs::GetPointMap > 
template<>
struct MD5Sum< ::map_msgs::GetPointMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_msgs::GetPointMap >::value();
  }
  static const char* value(const ::map_msgs::GetPointMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_msgs::GetPointMapResponse> should match 
// service_traits::DataType< ::map_msgs::GetPointMap > 
template<>
struct DataType< ::map_msgs::GetPointMapResponse>
{
  static const char* value()
  {
    return DataType< ::map_msgs::GetPointMap >::value();
  }
  static const char* value(const ::map_msgs::GetPointMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_MSGS_MESSAGE_GETPOINTMAP_H
